### PR TITLE
Remove unnecessary cast now that we are targeting C# 7.3 with latest compiler

### PR DESCRIPTION
**Pull request by ahsonkhan**
Leftover change from https://github.com/dotnet/corefxlab/pull/2161

### CODE REVIEW

**Comment by ahsonkhan** [comment]
FYI, @MisinformedDNA, @JeremyKuhne 

https://ci.dot.net/job/dotnet_corefxlab/job/master/job/ubuntu16.04_release_prtest/1979/console
```text
15:06:41 Building and running tests for project tests/System.IO.FileSystem.Watcher.Polling.Tests/System.IO.FileSystem.Watcher.Polling.Tests.csproj...
15:06:41 Test run for /mnt/j/workspace/dotnet_corefxlab/master/ubuntu16.04_release_prtest/tests/System.IO.FileSystem.Watcher.Polling.Tests/bin/Release/netcoreapp2.1/System.IO.FileSystem.Watcher.Polling.Tests.dll(.NETCoreApp,Version=v2.1)
15:06:41 Microsoft (R) Test Execution Command Line Tool Version 15.7.0
15:06:41 Copyright (c) Microsoft Corporation.  All rights reserved.
15:06:41 
15:06:42 Starting test execution, please wait...
15:06:45 The active test run was aborted. Reason: Unhandled Exception: System.ObjectDisposedException: Cannot access a disposed object.
15:06:45    at System.Threading.TimerQueueTimer.Change(UInt32 dueTime, UInt32 period)
15:06:45    at System.IO.PollingFileSystemWatcher.TimerHandler(Object context) in /mnt/j/workspace/dotnet_corefxlab/master/ubuntu16.04_release_prtest/src/System.IO.FileSystem.Watcher.Polling/System/IO/PollingFileSystemWatcher.cs:line 208
15:06:45    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
15:06:45 --- End of stack trace from previous location where exception was thrown ---
15:06:45    at System.Threading.TimerQueueTimer.CallCallback()
15:06:45    at System.Threading.TimerQueueTimer.Fire()
15:06:45    at System.Threading.ThreadPoolWorkQueue.Dispatch()
15:06:45 
15:06:45 
15:06:45 Total tests: Unknown. Passed: 17. Failed: 0. Skipped: 0.
15:06:45 Test Run Aborted.
15:06:45 Test execution time: 3.1382 Seconds
15:06:45 Some tests failed in project tests/System.IO.FileSystem.Watcher.Polling.Tests/System.IO.FileSystem.Watcher.Polling.Tests.csproj
```

**Comment by ahsonkhan** [comment]
> I'd like somebody from the compiler team to chime in just to ensure that compiling in this manner from the command line is supported.

@agocke - does this change look good to you?

> 15:06:42 Starting test execution, please wait...
15:06:45 The active test run was aborted. Reason: Unhandled Exception: System.ObjectDisposedException: Cannot access a disposed object.

@dotnet/dnceng, @maririos - is it possible for us to get the repro tool working in corefxlab as well? We have intermittent test failures here that are hard to reproduce and debug (especially in this instance since we can't tell the name of the failing test).

File: tools/common.props [hunk 1]
```diff
@@ -15,7 +15,5 @@
     <AssemblyOriginatorKeyFile>$(MSBuildThisFileDirectory)Key.snk</AssemblyOriginatorKeyFile>
     <LangVersion>latest</LangVersion>
   </PropertyGroup>
-  <ItemGroup Condition="'$(BuildingInsideVisualStudio)' != 'true'">
-    <PackageReference Include="Microsoft.NETCore.Compilers" Version="$(RoslynVersion)" PrivateAssets="All" />
```
Comment (agocke) [inline tools/common.props]: Why don't you need this anymore? Do you have a min req for .NET Core that is guaranteed to have C# 7.3?

Comment (ahsonkhan) [reply tools/common.props]: Yes, but it looks like the csc.dll within roslyn that comes with the dotnet cli that we install has a recent enough version and has support for C#7.3.(https://dotnet.myget.org/feed/roslyn/package/nuget/Microsoft.NETCore.Compilers/2.8.1-beta6-62911-06)
image

Otherwise, the code change in this PR to remove the cast wouldn't compile (based on recent overload resolution changes - https://github.com/dotnet/roslyn/pull/24756). That change wouldn't build on C#7.2.

> System\Buffers\Writer\BufferWriter_writable.cs(14,16): error CS0306: The type 'Span<byte>' may not be used as a type argument [D:\GitHub\Fork\corefxlab\src\System.Buffers.ReaderWriter\System.Buffers.ReaderWriter.csproj]
